version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: GreyOrange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  pact-broker:
    image: pactfoundation/pact-broker:latest
    depends_on:
      - postgres
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_USERNAME: guest
      PACT_BROKER_DATABASE_PASSWORD: guest
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: GreyOrange

      PACT_BROKER_BASIC_AUTH_USERNAME: admin
      PACT_BROKER_BASIC_AUTH_PASSWORD: password

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9292"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring


volumes:
  pact_postgres:
networks:
  monitoring:
    driver: bridge